### ISSUE TITLE
Read working date 500 error

### ISSUE THREAD

**Issue by Rundaer** [koddlo/sikiuares-cqrs-php#1]
Branch: v1
File: src/Booking/Infrastructure/Doctrine/Query/GetWorkingDayQuery.php

```
        $results = $queryBuilder->getQuery()->getArrayResult();

        if (empty($results)) {
            return null;
        }

        $bookings = [];
        foreach ($results as $result) {
            $bookings[] = new BookingDTO(
                $result['bookingFrom']->format('H:i'),
                $result['bookingTo']->format('H:i'),
                $result['bookerFirstName'],
                $result['bookerLastName'],
                $result['bookerEmail']
            );
        }
```

If there is no bookings for the working day, the error "...format() on null" on a non-existent date occurs.

**Comment by koddlo** [comment]
O... Thank you for reporting.

In the beginning, `workingDay` couldn't exist without `bookings`, but that changed later and I didn't adjust it at this point. Also there was no integration test for that case.

I fixed it in this [commit](https://github.com/koddlo/sikiuares-cqrs-php/commit/605fc37434f0c29034eb85a0c77bc02a2e0d236a). Also this change is applied in private repository.

**Comment by Rundaer** [comment]
Thanks, this was a quick one. Next time if i'll find something i'll create PR.
Gr8 book, btw :)
