### ISSUE TITLE
Couple remarks

### ISSUE THREAD

**Issue by sargath** [koddlo/sikiuares-cqrs-php#2]
Good stuff as always! 

# Tests
Maybe it's just me, although I think that Behat tests should fall into `tests/functional` or perhaps `tests/application` rather than `tests/integration` directory. Or potentially, as application tests, they should correspond to the controller namespaces.

# Readme 
`cp .env.local.dist .env.local` to provide example default values. 

Cheers! Thank you.

**Comment by koddlo** [comment]
It really depends on what naming convention you choose for the API tests. They are functional and integration specially if you app is only API. I agree, it can be also a `tests/functional`.

Yeah, right. File `env.local.dist` can be a better choice to copy. Probably, I'll fix it in the future.

Thanks!
